---
<<: !include "$common_config"

venue: LIQ
feeds:
  - address: "233.102.209.231:60012"
    interface: "$local_interface:60012"
  - address: "233.102.209.103:60013"
    interface: "$local_interface:60013"
recovery:
  address: "142.201.149.44:60026"
  delivery_address: "$local_interface:60062"
...
