file(GLOB_RECURSE
  header_files ${NEXUS_INCLUDE_PATH}/Nexus/FeeHandlingTests/*.hpp)
file(GLOB_RECURSE source_files ${NEXUS_SOURCE_PATH}/FeeHandlingTests/*.cpp)
add_executable(FeeHandlingTests ${header_files} ${source_files})
beam_configure_target(FeeHandlingTests DEPENDENCIES YAML)
target_compile_definitions(FeeHandlingTests PRIVATE YAML_CPP_STATIC_DEFINE)
set_source_files_properties(${header_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(FeeHandlingTests PUBLIC BeamRoutines)
add_custom_command(TARGET FeeHandlingTests POST_BUILD COMMAND FeeHandlingTests)
beam_install_target(FeeHandlingTests "${TEST_INSTALL_DIRECTORY}/$<CONFIG>")
