cmake_minimum_required(VERSION 3.28)
project(Nexus LANGUAGES CXX)
include(Config/project.cmake)
include(Config/dependencies.cmake)
include_directories(${NEXUS_INCLUDE_PATH})
include_directories(SYSTEM ${ASPEN_INCLUDE_PATH})
include_directories(SYSTEM ${BEAM_INCLUDE_PATH})
include_directories(SYSTEM ${BOOST_INCLUDE_PATH})
include_directories(SYSTEM ${CRYPTOPP_INCLUDE_PATH})
include_directories(SYSTEM ${DOCTEST_INCLUDE_PATH})
include_directories(SYSTEM ${HTRIE_INCLUDE_PATH})
include_directories(SYSTEM ${LUA_INCLUDE_PATH})
include_directories(SYSTEM ${MYSQL_INCLUDE_PATH})
include_directories(SYSTEM ${OPEN_SSL_INCLUDE_PATH})
include_directories(SYSTEM ${QUICK_FIX_INCLUDE_PATH})
include_directories(SYSTEM ${SQLITE_INCLUDE_PATH})
include_directories(SYSTEM ${TCLAP_INCLUDE_PATH})
include_directories(SYSTEM ${VIPER_INCLUDE_PATH})
include_directories(SYSTEM ${YAML_INCLUDE_PATH})
include_directories(SYSTEM ${ZLIB_INCLUDE_PATH})
link_directories(${BOOST_DEBUG_PATH})
link_directories(${BOOST_OPTIMIZED_PATH})
set(TEST_INSTALL_DIRECTORY "${PROJECT_BINARY_DIR}/Tests")
set(LIB_INSTALL_DIRECTORY "${PROJECT_BINARY_DIR}/Libraries")
include("${PROJECT_BINARY_DIR}/Dependencies/Beam/Beam/Config/targets.cmake")
add_subdirectory(Config/Accounting)
add_subdirectory(Config/AdministrationService)
add_subdirectory(Config/Backtester)
add_subdirectory(Config/ChartingService)
add_subdirectory(Config/Compliance)
add_subdirectory(Config/Definitions)
add_subdirectory(Config/DefinitionsService)
add_subdirectory(Config/FeeHandling)
add_subdirectory(Config/FixUtilities)
add_subdirectory(Config/MarketDataService)
add_subdirectory(Config/MoldUdp64)
add_subdirectory(Config/Nexus)
add_subdirectory(Config/OrderExecutionService)
add_subdirectory(Config/Parsers)
add_subdirectory(Config/Python)
add_subdirectory(Config/Queries)
add_subdirectory(Config/RiskService)
add_subdirectory(Config/SimulationMatcher)
add_subdirectory(Config/SoupBinTcp)
add_subdirectory(Config/Stamp)
add_subdirectory(Config/TechnicalAnalysis)
beam_configure_clean()
