---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

sampling: 100ms
enable_logging: false
country: CA
feed_timeout: 1s
gap_timeout: 1s
retry_interval: 1s
feeds:
  - address: "233.102.209.246:61070"
    interface: "$local_interface:61070"
  - address: "233.102.209.117:61071"
    interface: "$local_interface:61071"
recovery:
  address: "142.201.149.36:61072"
  interface: "$local_interface:0"
  delivery_address: "$local_interface:61073"
  timeout: 30s
...
