---
<<: !include "$common_config"

time_zone: America/Toronto
feeds:
  - address: "233.102.209.246:61070"
    interface: "$local_interface:61070"
recovery:
  address: "142.201.149.36:61072"
  delivery_address: "$local_interface:61073"
mpid_mappings: []
...
