#ifndef NEXUS_PYTHON_HPP
#define NEXUS_PYTHON_HPP
#include "Nexus/Python/Accounting.hpp"
#include "Nexus/Python/AdministrationService.hpp"
#include "Nexus/Python/Backtester.hpp"
#include "Nexus/Python/ChartingService.hpp"
#include "Nexus/Python/Compliance.hpp"
#include "Nexus/Python/Definitions.hpp"
#include "Nexus/Python/DefinitionsService.hpp"
#include "Nexus/Python/FeeHandling.hpp"
#include "Nexus/Python/MarketDataService.hpp"
#include "Nexus/Python/OrderExecutionService.hpp"
#include "Nexus/Python/Queries.hpp"
#include "Nexus/Python/RiskService.hpp"
#include "Nexus/Python/ServiceClients.hpp"
#include "Nexus/Python/ToPythonAdministrationClient.hpp"
#include "Nexus/Python/ToPythonChartingClient.hpp"
#include "Nexus/Python/ToPythonComplianceClient.hpp"
#include "Nexus/Python/ToPythonDefinitionsClient.hpp"
#include "Nexus/Python/ToPythonMarketDataClient.hpp"
#include "Nexus/Python/ToPythonMarketDataFeedClient.hpp"
#include "Nexus/Python/ToPythonOrderExecutionClient.hpp"
#include "Nexus/Python/ToPythonRiskClient.hpp"

#endif
