---
<<: !include "$common_config"

venue: NEOE
feeds:
  - address: "233.102.209.156:61203"
    interface: "$local_interface:61203"
  - address: "233.102.209.28:61211"
    interface: "$local_interface:61211"
recovery:
  address: "142.201.149.36:61223"
  delivery_address: "$local_interface:61233"
...
