---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

sampling: 100ms
enable_logging: false
partition: 1
venue: ASX
disseminating_venue: ASX
mpid: ASX
feed_timeout: 3s
gap_timeout: 5s
request_timeout: 1s
feeds:
  - name: D
    address: "233.71.185.137:21301"
    interface: "$local_interface:21301"
  - name: E
    address: "233.71.185.225:21401"
    interface: "$local_interface:21401"
rewind:
  address: "203.6.253.125:24001"
  interface: "$local_interface:0"
glimpse:
  address: "203.6.253.125:21801"
  interface: "$local_interface:0"
  username: "$glimpse_username"
  password: "$glimpse_password"
...
