file(GLOB_RECURSE source_files ${NEXUS_SOURCE_PATH}/StampTests/*.cpp)
add_executable(StampTests ${source_files})
beam_configure_target(StampTests DEPENDENCIES CRYPTOPP)
target_link_libraries(StampTests PUBLIC BeamRoutines)
add_custom_command(TARGET StampTests POST_BUILD COMMAND StampTests)
beam_install_target(StampTests "${TEST_INSTALL_DIRECTORY}/$<CONFIG>")
