---
service_locator:
  address: $service_locator_address
  username: $username
  password: $password

enable_logging: false
market: HKEX
disseminating_market: HKEX
mpid: HKEX
time_zone: Asia/Hong_Kong
sampling: 100ms
host: 239.1.1.3:51006
interface: $local_interface:51006
retransmission_host: 10.1.90.82:55455
snapshot_host: 239.1.1.13:51006
...
