file(GLOB_RECURSE header_files ${NEXUS_INCLUDE_PATH}/Nexus/QueriesTests/*.hpp)
file(GLOB_RECURSE source_files ${NEXUS_SOURCE_PATH}/QueriesTests/*.cpp)
add_executable(QueriesTests ${header_files} ${source_files})
beam_configure_target(QueriesTests)
set_source_files_properties(${header_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(QueriesTests PUBLIC BeamRoutines)
add_custom_command(TARGET QueriesTests POST_BUILD COMMAND QueriesTests)
beam_install_target(QueriesTests "${TEST_INSTALL_DIRECTORY}/$<CONFIG>")
