---
<<: !include "$common_config"

venue: CSE
feeds:
  - address: "233.102.209.227:60006"
    interface: "$local_interface:60006"
  - address: "233.102.209.99:60007"
    interface: "$local_interface:60007"
recovery:
  address: "142.201.149.44:60023"
  delivery_address: "$local_interface:60056"
...
