---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

sampling: 100ms
enable_logging: false
country: CA
feed_timeout: 1s
gap_timeout: 1s
retry_interval: 1s
feeds:
  - address: "233.102.209.227:60006"
    interface: "$local_interface:60006"
  - address: "233.102.209.99:60007"
    interface: "$local_interface:60007"
recovery:
  address: "142.201.149.44:60023"
  interface: "$local_interface:0"
  delivery_address: "$local_interface:60056"
  timeout: 30s
...
