---
<<: !include "$common_config"

time_zone: America/Toronto
feeds:
  - address: "233.102.209.221:61110"
    interface: "$local_interface:61110"
recovery:
  address: "142.201.149.36:61112"
  delivery_address: "$local_interface:61113"
...
