---
server:
  interface: "$local_interface:21200"
  addresses: ["$global_interface:21200", "$local_interface:21200"]

data_store:
  address: $mysql_address
  username: $mysql_username
  password: $mysql_password
  schema: $mysql_schema

service_locator:
  address: $service_locator_address
  username: telemetry_service
  password: $admin_password
...
