---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: true
unit: 2
venue: CXA
disseminating_venue: CXA
mpid: CXA
liveness: 3s
feeds:
  - name: A
    address: "233.218.133.80:30502"
    gap_address: "233.218.133.81:30502"
    interface: "$local_interface:30502"
  - name: B
    address: "233.218.133.96:30502"
    gap_address: "233.218.133.97:30502"
    interface: "$local_interface:30502"
...
