---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

sampling: 100ms
enable_logging: false
unit: 2
venue: ASX
disseminating_venue: CXA
mpid: CXA
liveness: 3s
feeds:
  - name: A
    address: "233.218.133.80:30502"
    gap_address: "233.218.133.81:30502"
    interface: "$local_interface:30502"
  - name: B
    address: "233.218.133.96:30502"
    gap_address: "233.218.133.97:30502"
    interface: "$local_interface:30502"
retransmission:
  address: "$retransmission_address"
  session_sub_id: "$retransmission_session_sub_id"
  username: "$retransmission_username"
  password: "$retransmission_password"
spin:
  address: "$spin_address"
  session_sub_id: "$spin_session_sub_id"
  username: "$spin_username"
  password: "$spin_password"
...
