file(GLOB_RECURSE source_files ${NEXUS_SOURCE_PATH}/DefinitionsTests/*.cpp)
add_executable(DefinitionsTests ${source_files})
beam_configure_target(DefinitionsTests DEPENDENCIES YAML)
target_compile_definitions(DefinitionsTests PRIVATE YAML_CPP_STATIC_DEFINE)
target_link_libraries(DefinitionsTests PUBLIC BeamRoutines)
add_custom_command(TARGET DefinitionsTests POST_BUILD COMMAND DefinitionsTests)
beam_install_target(DefinitionsTests "${TEST_INSTALL_DIRECTORY}/$<CONFIG>")
