file(GLOB_RECURSE source_files ${NEXUS_SOURCE_PATH}/SoupBinTcpTests/*.cpp)
add_executable(SoupBinTcpTests ${source_files})
beam_configure_target(SoupBinTcpTests DEPENDENCIES CRYPTOPP)
target_link_libraries(SoupBinTcpTests PUBLIC BeamRoutines)
add_custom_command(TARGET SoupBinTcpTests POST_BUILD COMMAND SoupBinTcpTests)
beam_install_target(SoupBinTcpTests "${TEST_INSTALL_DIRECTORY}/$<CONFIG>")
