---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

sampling: 100ms
enable_logging: false
partition: 4
venue: ASX
disseminating_venue: ASX
mpid: ASX
feed_timeout: 3s
request_timeout: 1s
feeds:
  - name: A
    address: "233.71.185.132:21004"
    interface: "$local_interface:21004"
  - name: B
    address: "233.71.185.148:21104"
    interface: "$local_interface:21104"
rewind:
  address: "203.6.253.126:24004"
  interface: "$local_interface:0"
glimpse:
  address: "203.6.253.126:21804"
  interface: "$local_interface:0"
  username: "$glimpse_username"
  password: "$glimpse_password"
...
