---
<<: !include "$common_config"

venue: TSX
feeds:
  - address: "233.102.209.224:60000"
    interface: "$local_interface:60000"
  - address: "233.102.209.96:60001"
    interface: "$local_interface:60001"
recovery:
  address: "142.201.149.44:60020"
  delivery_address: "$local_interface:60050"
...
