---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

sampling: 100ms
enable_logging: false
partition: 3
venue: ASX
disseminating_venue: ASX
mpid: ASX
feed_timeout: 3s
gap_timeout: 5s
request_timeout: 1s
feeds:
  - name: A
    address: "233.71.185.131:21003"
    interface: "$local_interface:21003"
  - name: B
    address: "233.71.185.147:21103"
    interface: "$local_interface:21103"
rewind:
  address: "203.6.253.126:24003"
  interface: "$local_interface:0"
glimpse:
  address: "203.6.253.126:21803"
  interface: "$local_interface:0"
  username: "$glimpse_username"
  password: "$glimpse_password"
...
