---
<<: !include "$common_config"

partition: 4
feeds:
  - name: D
    address: "233.71.185.140:21304"
    interface: "$local_interface:21304"
  - name: E
    address: "233.71.185.228:21404"
    interface: "$local_interface:21404"
rewind:
  address: "203.6.253.125:24004"
  interface: "$local_interface:0"
glimpse:
  address: "203.6.253.125:21804"
  interface: "$local_interface:0"
...
