---
<<: !include "$common_config"

venue: TSXV
feeds:
  - address: "233.102.209.234:61000"
    interface: "$local_interface:61000"
  - address: "233.102.209.106:61001"
    interface: "$local_interface:61001"
recovery:
  address: "142.201.149.44:60030"
  delivery_address: "$local_interface:60071"
...
