---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

sampling: 100ms
enable_logging: false
country: CA
venue: NEON
feed_timeout: 1s
gap_timeout: 1s
retry_interval: 1s
feeds:
  - address: "233.102.209.159:61206"
    interface: "$local_interface:61206"
  - address: "233.102.209.31:61214"
    interface: "$local_interface:61214"
recovery:
  address: "142.201.149.36:61226"
  interface: "$local_interface:0"
  delivery_address: "$local_interface:61236"
  timeout: 30s
...
