---
<<: !include "$common_config"

venue: NEON
feeds:
  - address: "233.102.209.159:61206"
    interface: "$local_interface:61206"
  - address: "233.102.209.31:61214"
    interface: "$local_interface:61214"
recovery:
  address: "142.201.149.36:61226"
  delivery_address: "$local_interface:61236"
...
