@ECHO OFF
SETLOCAL
PUSHD "%~dp0" || EXIT /B 1
IF "%PYTHON%" == "" SET "PYTHON=python"
IF "%SPHINXBUILD%" == "" SET "SPHINXBUILD=sphinx-build"
SET "TARGET=%~1"
IF NOT DEFINED TARGET SET "TARGET=help"
"%PYTHON%" build.py "%SPHINXBUILD%" "%TARGET%" source build %SPHINXOPTS%
SET "BUILD_RESULT=%ERRORLEVEL%"
POPD
EXIT /B %BUILD_RESULT%
