---
<<: !include "$common_config"

time_zone: America/Toronto
feeds:
  - address: "233.102.209.235:61002"
    interface: "$local_interface:61002"
recovery:
  address: "142.201.149.36:61020"
  delivery_address: "$local_interface:61050"
mpid_mappings: []
...
