---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
market: XSAP
disseminating_market: XSAP
mpid: SSE
time_zone: Asia/Tokyo
sampling: 100ms
host: 239.194.23.76:51576
interface: $local_interface:51576
...
