file(GLOB_RECURSE header_files ${NEXUS_INCLUDE_PATH}/Nexus/ParsersTests/*.hpp)
file(GLOB_RECURSE source_files ${NEXUS_SOURCE_PATH}/ParsersTests/*.cpp)
add_executable(ParsersTests ${header_files} ${source_files})
beam_configure_target(ParsersTests)
set_source_files_properties(${header_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(ParsersTests PUBLIC BeamRoutines)
add_custom_command(TARGET ParsersTests POST_BUILD COMMAND ParsersTests)
beam_install_target(ParsersTests "${TEST_INSTALL_DIRECTORY}/$<CONFIG>")
