---
<<: !include "$common_config"

venue: TSX
feeds:
  - address: "233.102.209.220:61105"
    interface: "$local_interface:61105"
  - address: "233.102.209.87:61106"
    interface: "$local_interface:61106"
recovery:
  address: "142.201.149.44:61107"
  delivery_address: "$local_interface:61108"
...
