---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

sampling: 100ms
enable_logging: false
country: CA
venue: TSX
rollover_time: "00:30:00"
feed_timeout: 1s
gap_timeout: 1s
retry_interval: 1s
feeds:
  - address: "233.102.209.220:61105"
    interface: "$local_interface:61105"
  - address: "233.102.209.87:61106"
    interface: "$local_interface:61106"
recovery:
  address: "142.201.149.44:61107"
  interface: "$local_interface:0"
  delivery_address: "$local_interface:61108"
  timeout: 30s
...
