---
<<: !include "$common_config"

venue: ALX
feeds:
  - address: "233.102.209.214:60028"
    interface: "$local_interface:60028"
  - address: "233.102.209.66:60029"
    interface: "$local_interface:60029"
recovery:
  address: "142.201.149.44:60091"
  delivery_address: "$local_interface:60092"
...
