---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
market: CXA
disseminating_market: CXA
mpid: CXA
is_time_and_sale: true
sampling: 100ms
host: "233.218.133.80:30502"
interface: "$local_interface:30502"
...
