---
<<: !include "$common_config"

time_zone: America/Toronto
feeds:
  - address: "233.102.209.228:60008"
    interface: "$local_interface:60008"
recovery:
  address: "142.201.149.36:60024"
  delivery_address: "$local_interface:60058"
mpid_mappings: []
...
