export default {
  BACKEND_API_ROOT_URL: '/api/',
  FADE_DURATION: 200,
  MIN_PRELOADER_DURATION: 1200,
  PRELOADER_SHOW_TIME: 500,
  INPUT_TIMEOUT_DURATION: 500,
  WHOLE_PAGE_PRELOADER_WIDTH: 49,
  WHOLE_PAGE_PRELOADER_HEIGHT: 60
};
