---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

sampling: 100ms
enable_logging: false
partition: 2
venue: ASX
disseminating_venue: ASX
mpid: ASX
feed_timeout: 3s
gap_timeout: 5s
request_timeout: 1s
feeds:
  - name: A
    address: "233.71.185.130:21002"
    interface: "$local_interface:21002"
  - name: B
    address: "233.71.185.146:21102"
    interface: "$local_interface:21102"
rewind:
  address: "203.6.253.126:24002"
  interface: "$local_interface:0"
glimpse:
  address: "203.6.253.126:21802"
  interface: "$local_interface:0"
  username: "$glimpse_username"
  password: "$glimpse_password"
...
