---
<<: !include "$common_config"

venue: NEOE
feeds:
  - address: "233.102.209.154:61201"
    interface: "$local_interface:61201"
  - address: "233.102.209.26:61209"
    interface: "$local_interface:61209"
recovery:
  address: "142.201.149.36:61221"
  delivery_address: "$local_interface:61231"
...
