---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
market: XFKA
disseminating_market: XFKA
mpid: FSE
time_zone: Asia/Tokyo
sampling: 100ms
host: 239.194.23.74:51574
interface: $local_interface:51574
...
