---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

enable_logging: false
feed_timeout: 1s
gap_timeout: 1s
retry_interval: 1s
receive_buffer: 134217728

feeds:
  - address: "233.102.209.217:60103"
    interface: "$local_interface"
  - address: "233.102.209.57:60107"
    interface: "$local_interface"

recovery:
  address: "142.201.149.44:60113"
  interface: "$local_interface"
  delivery_address: "$local_interface:60123"
  timeout: 30s
...
