cmake_minimum_required(VERSION 3.28)
project(Scratch LANGUAGES CXX)
include(../../Nexus/Config/project.cmake)
include(../../Nexus/Config/dependencies.cmake)
include("${beam_configuration}/targets.cmake")
include_directories(${NEXUS_INCLUDE_PATH})
link_directories(${BOOST_DEBUG_PATH})
link_directories(${BOOST_OPTIMIZED_PATH})
include_directories(${PROJECT_BINARY_DIR})
set(header_files "${PROJECT_BINARY_DIR}/Version.hpp")
file(GLOB_RECURSE source_files Source/*.cpp)
add_executable(Scratch ${header_files} ${source_files})
beam_configure_target(Scratch DEPENDENCIES
  ASPEN BEAM BOOST CRYPTOPP HTRIE MYSQL OPEN_SSL OPEN_SSL_BASE SQLITE TCLAP
  VIPER YAML ZLIB)
target_link_libraries(Scratch PUBLIC BeamRoutines)
target_compile_definitions(Scratch PRIVATE YAML_CPP_STATIC_DEFINE)
set_source_files_properties(${header_files} PROPERTIES HEADER_FILE_ONLY TRUE)
if(MSVC)
  target_link_options(Scratch PRIVATE /SAFESEH:NO)
endif()
if(WIN32)
  target_link_libraries(Scratch PUBLIC Crypt32.lib shlwapi)
endif()
beam_install_target(Scratch "${PROJECT_BINARY_DIR}/Application")
beam_configure_clean()
