---
<<: !include "$common_config"

venue: NEOE
feeds:
  - address: "233.102.209.157:61204"
    interface: "$local_interface:61204"
  - address: "233.102.209.29:61212"
    interface: "$local_interface:61212"
recovery:
  address: "142.201.149.36:61224"
  delivery_address: "$local_interface:61234"
...
