---
<<: !include "$common_config"

venue: MATN
feeds:
  - address: "233.102.209.216:60102"
    interface: "$local_interface:60102"
  - address: "233.102.209.56:60106"
    interface: "$local_interface:60106"
recovery:
  address: "142.201.149.44:60112"
  delivery_address: "$local_interface:60122"
...
