---
<<: !include "$common_config"

service: inside
feeds:
  - address: "224.0.23.214:21004"
    interface: "$local_interface:21004"
  - address: "224.0.23.231:21004"
    interface: "$local_interface:21004"

# recovery:
#   address: "192.26.98.86:21100"
#   interface: "$local_interface:0"
#   sender: "$sender"
#   timeout: 1s

# snapshot:
#   address: "224.0.23.214:21005"
#   interface: "$local_interface:21005"
#   timeout: 1s
#   retries: 1
#   server:
#     address: "192.26.98.86:21100"
#     interface: "$local_interface:0"
#     sender: "$sender"
#     timeout: 1s
...
