cmake_minimum_required(VERSION 3.28)
file(REAL_PATH "${CMAKE_CURRENT_LIST_DIR}/.." source_directory)
file(REAL_PATH "${DEPENDENCIES_DIRECTORY}" dependencies_directory)
set(cache_file "${dependencies_directory}/.nexus_configure_complete")

function(fingerprint result)
  file(GLOB inputs
    "${source_directory}/setup.*"
    "${source_directory}/Config/lua.cmake"
    "${dependencies_directory}/*/.*_complete")
  list(APPEND inputs "${CMAKE_CURRENT_FUNCTION_LIST_FILE}")
  set(revisions)
  foreach(repository Beam aspen viper)
    set(directory "${dependencies_directory}/${repository}")
    file(GLOB scripts "${directory}/setup.*" "${directory}/Beam/setup.*")
    list(APPEND inputs ${scripts})
    if(EXISTS "${directory}/.git")
      execute_process(COMMAND git -C "${directory}" rev-parse HEAD
        RESULT_VARIABLE status OUTPUT_VARIABLE revision
        ERROR_VARIABLE error OUTPUT_STRIP_TRAILING_WHITESPACE)
      if(NOT status EQUAL 0)
        message(FATAL_ERROR "Unable to read ${repository} revision: ${error}")
      endif()
      string(APPEND revisions "${directory}:${revision}\n")
    endif()
  endforeach()
  list(SORT inputs)
  set(contents "${revisions}")
  foreach(input IN LISTS inputs)
    file(SHA256 "${input}" hash)
    string(APPEND contents "${input}:${hash}\n")
  endforeach()
  string(SHA256 hash "${contents}")
  set(${result} "${hash}" PARENT_SCOPE)
endfunction()

fingerprint(current)
if(EXISTS "${cache_file}")
  file(READ "${cache_file}" previous)
  if(previous STREQUAL current)
    return()
  endif()
endif()
file(REMOVE "${cache_file}")
if(CMAKE_HOST_WIN32)
  set(command cmd /c CALL "${source_directory}/setup.bat")
else()
  set(command "${source_directory}/setup.sh")
endif()
execute_process(COMMAND ${command}
  WORKING_DIRECTORY "${dependencies_directory}" RESULT_VARIABLE status)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Dependency setup failed: ${status}")
endif()
fingerprint(current)
file(WRITE "${cache_file}" "${current}")
