if(WIN32)
  include("${CMAKE_CURRENT_LIST_DIR}/dependencies.windows.cmake")
else()
  include("${CMAKE_CURRENT_LIST_DIR}/dependencies.posix.cmake")
endif()
set(HTRIE_INCLUDE_PATH "${PROJECT_BINARY_DIR}/Dependencies/hat-trie-0.7.0/include")
