include("${DEPENDENCIES_PATH}/Beam/Beam/Config/dependencies.cmake")
set(NEXUS_INCLUDE_PATH "${CMAKE_CURRENT_LIST_DIR}/../Include")
set(NEXUS_SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}/../Source")
set(BEAM_INCLUDE_PATH "${DEPENDENCIES_PATH}/Beam/Beam/Include")
set(BEAM_PYTHON_LIBRARY_DEBUG_PATH "${DEPENDENCIES_PATH}/Beam/Beam/Libraries/Debug/beam.lib")
set(BEAM_PYTHON_LIBRARY_OPTIMIZED_PATH "${DEPENDENCIES_PATH}/Beam/Beam/Libraries/Release/beam.lib")
