include(
  "${PROJECT_BINARY_DIR}/Dependencies/Beam/Beam/Config/dependencies.cmake")
set(NEXUS_INCLUDE_PATH "${CMAKE_CURRENT_LIST_DIR}/../Include")
set(NEXUS_SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}/../Source")
set(BEAM_INCLUDE_PATH "${PROJECT_BINARY_DIR}/Dependencies/Beam/Beam/Include")
set(BEAM_PYTHON_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/Beam/Beam/Libraries/Debug/_beam.lib")
set(BEAM_PYTHON_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/Beam/Beam/Libraries/Release/_beam.lib")
set(LUA_INCLUDE_PATH "${PROJECT_BINARY_DIR}/Dependencies/lua-5.4.4/src")
set(LUA_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/lua-5.4.4/src/Debug/lua.lib")
set(LUA_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/lua-5.4.4/src/Release/lua.lib")
set(QT_ROOT "${PROJECT_BINARY_DIR}/Dependencies/qt-5.15.2")
set(QT_INCLUDE_PATH "${QT_ROOT}/qtbase/include")
set(QT_CORE_INCLUDE_PATH "${QT_INCLUDE_PATH}/QtCore")
set(QT_GUI_INCLUDE_PATH "${QT_INCLUDE_PATH}/QtGui")
set(QT_WIDGETS_INCLUDE_PATH "${QT_INCLUDE_PATH}/QtWidgets")
set(QT_LIBRARY_DEBUG_PATH "${QT_ROOT}/qtbase/lib")
set(QT_LIBRARY_OPTIMIZED_PATH "${QT_ROOT}/qtbase/lib")
set(QT_ACCESS_LIBRARY_DEBUG_PATH
  "${QT_LIBRARY_DEBUG_PATH}/Qt5AccessibilitySupportd.lib")
set(QT_ACCESS_LIBRARY_OPTIMIZED_PATH
  "${QT_LIBRARY_OPTIMIZED_PATH}/Qt5AccessibilitySupport.lib")
set(QT_CORE_LIBRARY_DEBUG_PATH "${QT_LIBRARY_DEBUG_PATH}/Qt5Cored.lib")
set(QT_CORE_LIBRARY_OPTIMIZED_PATH "${QT_LIBRARY_OPTIMIZED_PATH}/Qt5Core.lib")
set(QT_EVENT_LIBRARY_DEBUG_PATH
  "${QT_LIBRARY_DEBUG_PATH}/Qt5EventDispatcherSupportd.lib")
set(QT_EVENT_LIBRARY_OPTIMIZED_PATH
  "${QT_LIBRARY_OPTIMIZED_PATH}/Qt5EventDispatcherSupport.lib")
set(QT_FONT_LIBRARY_DEBUG_PATH
  "${QT_LIBRARY_DEBUG_PATH}/Qt5FontDatabaseSupportd.lib")
set(QT_FONT_LIBRARY_OPTIMIZED_PATH
  "${QT_LIBRARY_OPTIMIZED_PATH}/Qt5FontDatabaseSupport.lib")
set(QT_FREETYPE_LIBRARY_DEBUG_PATH "${QT_LIBRARY_DEBUG_PATH}/qtfreetyped.lib")
set(QT_FREETYPE_LIBRARY_OPTIMIZED_PATH
  "${QT_LIBRARY_OPTIMIZED_PATH}/qtfreetype.lib")
set(QT_HBNG_LIBRARY_DEBUG_PATH "${QT_LIBRARY_DEBUG_PATH}/qtharfbuzzd.lib")
set(QT_HBNG_LIBRARY_OPTIMIZED_PATH
  "${QT_LIBRARY_OPTIMIZED_PATH}/qtharfbuzz.lib")
set(QT_GUI_LIBRARY_DEBUG_PATH "${QT_LIBRARY_DEBUG_PATH}/Qt5Guid.lib")
set(QT_GUI_LIBRARY_OPTIMIZED_PATH "${QT_LIBRARY_OPTIMIZED_PATH}/Qt5Gui.lib")
set(QT_MAIN_LIBRARY_DEBUG_PATH "${QT_LIBRARY_DEBUG_PATH}/QtMaind.lib")
set(QT_MAIN_LIBRARY_OPTIMIZED_PATH "${QT_LIBRARY_OPTIMIZED_PATH}/QtMain.lib")
set(QT_PCRE_LIBRARY_DEBUG_PATH "${QT_LIBRARY_DEBUG_PATH}/qtpcre2d.lib")
set(QT_PCRE_LIBRARY_OPTIMIZED_PATH "${QT_LIBRARY_OPTIMIZED_PATH}/qtpcre2.lib")
set(QT_PNG_LIBRARY_DEBUG_PATH "${QT_LIBRARY_DEBUG_PATH}/qtlibpngd.lib")
set(QT_PNG_LIBRARY_OPTIMIZED_PATH "${QT_LIBRARY_OPTIMIZED_PATH}/qtlibpng.lib")
set(QT_THEME_LIBRARY_DEBUG_PATH "${QT_LIBRARY_DEBUG_PATH}/Qt5ThemeSupportd.lib")
set(QT_THEME_LIBRARY_OPTIMIZED_PATH
  "${QT_LIBRARY_OPTIMIZED_PATH}/Qt5ThemeSupport.lib")
set(QT_WIDGETS_LIBRARY_DEBUG_PATH "${QT_LIBRARY_DEBUG_PATH}/Qt5Widgetsd.lib")
set(QT_WIDGETS_LIBRARY_OPTIMIZED_PATH
  "${QT_LIBRARY_OPTIMIZED_PATH}/Qt5Widgets.lib")
set(QT_WINDOWS_LIBRARY_DEBUG_PATH
  "${QT_ROOT}/qtbase/plugins/platforms/qwindowsd.lib")
set(QT_WINDOWS_LIBRARY_OPTIMIZED_PATH
  "${QT_ROOT}/qtbase/plugins/platforms/qwindows.lib")
set(QT_WINDOWS_ACCESSIBILITY_LIBRARY_DEBUG_PATH
  "${QT_LIBRARY_DEBUG_PATH}/Qt5WindowsUIAutomationSupportd.lib")
set(QT_WINDOWS_ACCESSIBILITY_LIBRARY_OPTIMIZED_PATH
  "${QT_LIBRARY_OPTIMIZED_PATH}/Qt5WindowsUIAutomationSupport.lib")
set(QUICK_FIX_INCLUDE_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/quickfix-v.1.15.1/include")
set(QUICK_FIX_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/quickfix-v.1.15.1/lib/debug/quickfix.lib")
set(QUICK_FIX_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/quickfix-v.1.15.1/lib/quickfix.lib")
