cmake_minimum_required(VERSION 3.28)
if(STRIP_COMPONENTS EQUAL 0)
  file(ARCHIVE_EXTRACT INPUT "${ARCHIVE}" DESTINATION "${DESTINATION}")
  return()
endif()
if(NOT STRIP_COMPONENTS EQUAL 1)
  message(FATAL_ERROR "Unsupported archive strip count: ${STRIP_COMPONENTS}")
endif()
get_filename_component(destination "${DESTINATION}" ABSOLUTE)
set(directory "${destination}/.extract")
cmake_path(IS_PREFIX destination "${directory}" NORMALIZE is_extract_directory)
if(NOT is_extract_directory)
  message(FATAL_ERROR "Invalid archive extraction directory.")
endif()
file(REMOVE_RECURSE "${directory}")
file(ARCHIVE_EXTRACT INPUT "${ARCHIVE}" DESTINATION "${directory}")
file(GLOB entries LIST_DIRECTORIES TRUE "${directory}/*")
foreach(entry IN LISTS entries)
  if(IS_DIRECTORY "${entry}")
    file(COPY "${entry}/" DESTINATION "${destination}")
  endif()
endforeach()
file(REMOVE_RECURSE "${directory}")
