cmake_minimum_required(VERSION 3.28)
file(REAL_PATH "${BUILD_DIRECTORY}" build_directory)
set(snapshot "${build_directory}/CMakeFiles/generated_files_snapshot.txt")
set(manifest "${build_directory}/CMakeFiles/generated_files.txt")
if(NOT DEPENDENCIES_DIRECTORY AND EXISTS "${build_directory}/CMakeCache.txt")
  load_cache("${build_directory}" READ_WITH_PREFIX cached_ D)
  set(DEPENDENCIES_DIRECTORY "${cached_D}")
endif()
if(DEPENDENCIES_DIRECTORY)
  cmake_path(ABSOLUTE_PATH DEPENDENCIES_DIRECTORY
    BASE_DIRECTORY "${build_directory}" OUTPUT_VARIABLE dependencies)
  if(EXISTS "${dependencies}")
    file(REAL_PATH "${dependencies}" dependencies)
  else()
    cmake_path(NORMAL_PATH dependencies)
  endif()
endif()

function(collect directory result)
  file(GLOB children LIST_DIRECTORIES TRUE "${directory}/*")
  set(entries)
  foreach(child IN LISTS children)
    cmake_path(GET child FILENAME name)
    if(name STREQUAL "Dependencies" OR name STREQUAL ".git" OR
        child STREQUAL dependencies OR child STREQUAL snapshot OR
        child STREQUAL manifest)
      continue()
    endif()
    file(RELATIVE_PATH path "${build_directory}" "${child}")
    if(IS_DIRECTORY "${child}" AND NOT IS_SYMLINK "${child}")
      list(APPEND entries "D ${path}")
      collect("${child}" descendants)
      list(APPEND entries ${descendants})
    else()
      list(APPEND entries "F ${path}")
    endif()
  endforeach()
  set(${result} "${entries}" PARENT_SCOPE)
endfunction()

function(record)
  file(STRINGS "${snapshot}" previous)
  collect("${build_directory}" entries)
  if(previous)
    list(REMOVE_ITEM entries ${previous})
  endif()
  if(EXISTS "${manifest}")
    file(STRINGS "${manifest}" recorded)
    list(APPEND entries ${recorded})
  endif()
  list(REMOVE_DUPLICATES entries)
  list(SORT entries)
  list(JOIN entries "\n" contents)
  file(WRITE "${manifest}" "${contents}\n")
  file(REMOVE "${snapshot}")
endfunction()

if(ACTION STREQUAL "begin")
  collect("${build_directory}" entries)
  list(JOIN entries "\n" contents)
  file(WRITE "${snapshot}" "${contents}\n")
elseif(ACTION STREQUAL "end")
  record()
elseif(ACTION STREQUAL "clean")
  file(REMOVE "${snapshot}")
  if(NOT EXISTS "${manifest}")
    return()
  endif()
  file(STRINGS "${manifest}" entries)
  set(files)
  set(directories)
  set(comparison_directory "${build_directory}")
  if(CMAKE_HOST_WIN32)
    string(TOLOWER "${comparison_directory}" comparison_directory)
  endif()
  foreach(entry IN LISTS entries)
    if(NOT entry MATCHES "^([FD]) (.+)$")
      message(FATAL_ERROR "Invalid generated file entry: ${entry}")
    endif()
    set(type "${CMAKE_MATCH_1}")
    set(path "${build_directory}/${CMAKE_MATCH_2}")
    cmake_path(NORMAL_PATH path)
    if(NOT EXISTS "${path}" AND NOT IS_SYMLINK "${path}")
      continue()
    endif()
    cmake_path(GET path PARENT_PATH parent)
    file(REAL_PATH "${parent}" parent)
    cmake_path(GET path FILENAME name)
    set(comparison_path "${parent}/${name}")
    if(CMAKE_HOST_WIN32)
      string(TOLOWER "${comparison_path}" comparison_path)
    endif()
    cmake_path(IS_PREFIX comparison_directory "${comparison_path}"
      NORMALIZE is_output)
    if(NOT is_output OR comparison_path STREQUAL comparison_directory)
      message(FATAL_ERROR "Invalid generated file: ${path}")
    endif()
    if(type STREQUAL "F")
      if(IS_DIRECTORY "${path}" AND NOT IS_SYMLINK "${path}")
        message(FATAL_ERROR "Expected a generated file: ${path}")
      endif()
      list(APPEND files "${path}")
    elseif(IS_DIRECTORY "${path}" AND NOT IS_SYMLINK "${path}")
      list(APPEND directories "${path}")
    endif()
  endforeach()
  foreach(path IN LISTS files)
    file(REMOVE "${path}")
    if(EXISTS "${path}" OR IS_SYMLINK "${path}")
      message(FATAL_ERROR "Failed to remove ${path}.")
    endif()
  endforeach()
  file(REMOVE "${manifest}")
  if(EXISTS "${manifest}")
    message(FATAL_ERROR "Failed to remove ${manifest}.")
  endif()
  list(SORT directories ORDER DESCENDING)
  foreach(path IN LISTS directories)
    file(GLOB children "${path}/*")
    if(NOT children)
      file(REMOVE_RECURSE "${path}")
      if(EXISTS "${path}")
        message(FATAL_ERROR "Failed to remove ${path}.")
      endif()
    endif()
  endforeach()
else()
  message(FATAL_ERROR "Unknown generated file action: ${ACTION}")
endif()
