cmake_minimum_required(VERSION 3.28)
load_cache("${BUILD_DIRECTORY}" READ_WITH_PREFIX cached_
  CMAKE_BUILD_TYPE CMAKE_CONFIGURATION_TYPES CMAKE_GENERATOR
  CMAKE_GENERATOR_INSTANCE CMAKE_GENERATOR_PLATFORM CMAKE_MAKE_PROGRAM
  CMAKE_PROJECT_NAME)
set(configurations ${cached_CMAKE_CONFIGURATION_TYPES})
if(NOT configurations)
  if(cached_CMAKE_BUILD_TYPE)
    set(configurations "${cached_CMAKE_BUILD_TYPE}")
  else()
    set(configurations Release)
  endif()
endif()
if(cached_CMAKE_GENERATOR MATCHES "^Visual Studio ")
  set(solution "${BUILD_DIRECTORY}/${cached_CMAKE_PROJECT_NAME}.slnx")
  if(NOT EXISTS "${solution}")
    set(solution "${BUILD_DIRECTORY}/${cached_CMAKE_PROJECT_NAME}.sln")
  endif()
  if(NOT EXISTS "${solution}")
    return()
  endif()
  find_program(msbuild NAMES MSBuild.exe HINTS
    "${cached_CMAKE_GENERATOR_INSTANCE}/MSBuild/Current/Bin"
    "${cached_CMAKE_GENERATOR_INSTANCE}/MSBuild/15.0/Bin"
    REQUIRED NO_CACHE)
elseif(cached_CMAKE_GENERATOR MATCHES "Makefiles|JOM")
  if(NOT EXISTS "${BUILD_DIRECTORY}/CMakeFiles/Makefile2")
    return()
  endif()
  set(configurations clean)
elseif(cached_CMAKE_GENERATOR MATCHES "^Ninja")
  if(NOT EXISTS "${BUILD_DIRECTORY}/build.ninja")
    return()
  endif()
  if(cached_CMAKE_GENERATOR STREQUAL "Ninja")
    set(configurations clean)
  endif()
elseif(cached_CMAKE_GENERATOR STREQUAL "Xcode")
  set(project "${BUILD_DIRECTORY}/${cached_CMAKE_PROJECT_NAME}.xcodeproj")
  if(NOT EXISTS "${project}")
    return()
  endif()
  if(NOT cached_CMAKE_MAKE_PROGRAM)
    find_program(cached_CMAKE_MAKE_PROGRAM NAMES xcodebuild REQUIRED NO_CACHE)
  endif()
else()
  message(FATAL_ERROR "Unsupported clean generator: ${cached_CMAKE_GENERATOR}")
endif()
foreach(configuration IN LISTS configurations)
  if(cached_CMAKE_GENERATOR MATCHES "^Visual Studio ")
    set(command "${msbuild}" "${solution}" /t:Clean /nologo /verbosity:minimal
      "/p:Configuration=${configuration}"
      /p:ExtensionsToDeleteOnClean=__no_files__)
    if(cached_CMAKE_GENERATOR_PLATFORM)
      string(REGEX REPLACE ",.*$" ""
        platform "${cached_CMAKE_GENERATOR_PLATFORM}")
      if(platform)
        list(APPEND command "/p:Platform=${platform}")
      endif()
    endif()
  elseif(cached_CMAKE_GENERATOR MATCHES "Makefiles|JOM")
    set(command "${cached_CMAKE_MAKE_PROGRAM}" -f CMakeFiles/Makefile2 clean)
  elseif(cached_CMAKE_GENERATOR MATCHES "^Ninja")
    set(command "${cached_CMAKE_MAKE_PROGRAM}")
    if(cached_CMAKE_GENERATOR STREQUAL "Ninja Multi-Config")
      list(APPEND command -f "build-${configuration}.ninja")
    endif()
    list(APPEND command -t clean)
  else()
    set(command "${cached_CMAKE_MAKE_PROGRAM}" -project "${project}"
      -alltargets -configuration "${configuration}" clean)
  endif()
  execute_process(COMMAND ${command} WORKING_DIRECTORY "${BUILD_DIRECTORY}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT output STREQUAL "")
    message("${output}")
  endif()
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Failed to clean ${configuration}: ${result}")
  endif()
endforeach()
