cmake_minimum_required(VERSION 3.28)
if(NOT IS_DIRECTORY "${BUILD_DIRECTORY}")
  message(FATAL_ERROR "Invalid build directory: ${BUILD_DIRECTORY}")
endif()
file(REAL_PATH "${BUILD_DIRECTORY}" build_directory)
set(dependencies "${build_directory}/Dependencies")
cmake_path(IS_PREFIX build_directory "${dependencies}" NORMALIZE is_dependency)
if(NOT is_dependency)
  message(FATAL_ERROR "Invalid dependencies directory: ${dependencies}")
endif()
file(REMOVE_RECURSE "${dependencies}")
if(EXISTS "${dependencies}" OR IS_SYMLINK "${dependencies}")
  message(FATAL_ERROR "Failed to remove ${dependencies}.")
endif()
