---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: true
unit: 1
venue: CXA
disseminating_venue: CXA
mpid: CXA
liveness: 3s
feeds:
  - name: PRIMARY
    address: "233.218.133.1:6001"
    interface: "$local_interface:6001"
  - name: BACKUP
    address: "233.218.133.65:7001"
    interface: "$local_interface:7001"
...
