---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

sampling: 100ms
enable_logging: false
unit: 1
venue: CXA
disseminating_venue: CXA
mpid: CXA
liveness: 3s
feeds:
  - name: A
    address: "233.218.133.80:30501"
    gap_address: "233.218.133.81:30501"
    interface: "$local_interface:30501"
  - name: B
    address: "233.218.133.96:30501"
    gap_address: "233.218.133.97:30501"
    interface: "$local_interface:30501"
retransmission:
  address: "202.94.78.7:39001"
  session_sub_id: "$retransmission_session_sub_id"
  username: "$retransmission_username"
  password: "$retransmission_password"
...
