---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
market: XNGO
disseminating_market: XNGO
mpid: NSE
time_zone: Asia/Tokyo
sampling: 100ms
host: 239.194.23.72:51572
interface: $local_interface:51572
...
