---
<<: !include "$common_config"

venue: ICX
feeds:
  - address: "233.102.209.239:61010"
    interface: "$local_interface:61010"
  - address: "233.102.209.111:61011"
    interface: "$local_interface:61011"
recovery:
  address: "142.201.149.44:61024"
  delivery_address: "$local_interface:61058"
...
