---
<<: !include "$common_config"

time_zone: America/Toronto
feeds:
  - address: "233.102.209.236:61004"
    interface: "$local_interface:61004"
recovery:
  address: "142.201.149.36:61021"
  delivery_address: "$local_interface:61052"
...
