file(GLOB_RECURSE source_files ${NEXUS_SOURCE_PATH}/MoldUdp64Tests/*.cpp)
add_executable(MoldUdp64Tests ${source_files})
beam_configure_target(MoldUdp64Tests DEPENDENCIES CRYPTOPP)
target_link_libraries(MoldUdp64Tests PUBLIC BeamRoutines)
add_custom_command(TARGET MoldUdp64Tests POST_BUILD COMMAND MoldUdp64Tests)
beam_install_target(MoldUdp64Tests "${TEST_INSTALL_DIRECTORY}/$<CONFIG>")
