---
<<: !include "$common_config"

venue: NEON
feeds:
  - address: "233.102.209.161:61208"
    interface: "$local_interface:61208"
  - address: "233.102.209.33:61216"
    interface: "$local_interface:61216"
recovery:
  address: "142.201.149.36:61228"
  delivery_address: "$local_interface:61238"
...
