---
<<: !include "$common_config"

venue: TSX
feeds:
  - address: "233.102.209.219:61100"
    interface: "$local_interface:61100"
  - address: "233.102.209.86:61101"
    interface: "$local_interface:61101"
recovery:
  address: "142.201.149.44:61102"
  delivery_address: "$local_interface:61103"
...
