---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
market: XTKS
disseminating_market: XTKS
mpid: TSE
time_zone: Asia/Tokyo
sampling: 100ms
host: 239.194.23.62:51562
interface: $local_interface:51562
...
