---
<<: !include "$common_config"

venue: CX2
feeds:
  - address: "233.102.209.244:61019"
    interface: "$local_interface:61019"
  - address: "233.102.209.115:61020"
    interface: "$local_interface:61020"
recovery:
  address: "142.201.149.44:61028"
  delivery_address: "$local_interface:61066"
...
