---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

sampling: 100ms
enable_logging: false
country: CA
venue: CX2
rollover_time: "00:30:00"
feed_timeout: 1s
gap_timeout: 1s
retry_interval: 1s
feeds:
  - address: "233.102.209.244:61019"
    interface: "$local_interface:61019"
  - address: "233.102.209.115:61020"
    interface: "$local_interface:61020"
recovery:
  address: "142.201.149.44:61028"
  interface: "$local_interface:0"
  delivery_address: "$local_interface:61066"
  timeout: 30s
...
