---
<<: !include "$common_config"

venue: CSE2
feeds:
  - address: "233.102.209.241:60027"
    interface: "$local_interface:60027"
  - address: "233.102.209.113:60026"
    interface: "$local_interface:60026"
recovery:
  address: "142.201.149.44:60037"
  delivery_address: "$local_interface:60089"
...
