---
service_locator:
  address: "$service_locator_address"
  username: "$username"
  password: "$admin_password"

enable_logging: false
feed_timeout: 1s
gap_timeout: 1s
retry_interval: 1s
receive_buffer: 134217728

feeds:
  - address: "233.102.209.241:60027"
    interface: "$local_interface"
  - address: "233.102.209.113:60026"
    interface: "$local_interface"

recovery:
  address: "142.201.149.44:60037"
  interface: "$local_interface"
  delivery_address: "$local_interface:60089"
  timeout: 30s
...
