---
<<: !include "$common_config"

venue: CXD
feeds:
  - address: "233.102.209.251:61089"
    interface: "$local_interface:61089"
  - address: "233.102.209.122:61090"
    interface: "$local_interface:61090"
recovery:
  address: "142.201.149.44:61091"
  delivery_address: "$local_interface:61092"
...
