---
<<: !include "$common_config"

venue: XATS
feeds:
  - address: "233.102.209.230:60010"
    interface: "$local_interface:60010"
  - address: "233.102.209.102:60011"
    interface: "$local_interface:60011"
recovery:
  address: "142.201.149.44:60025"
  delivery_address: "$local_interface:60060"
...
