file(GLOB_RECURSE source_files ${NEXUS_SOURCE_PATH}/BacktesterTests/*.cpp)
add_executable(BacktesterTests ${source_files})
beam_configure_target(BacktesterTests DEPENDENCIES CRYPTOPP)
target_link_libraries(BacktesterTests PUBLIC BeamRoutines)
add_custom_command(TARGET BacktesterTests POST_BUILD COMMAND BacktesterTests)
beam_install_target(BacktesterTests "${TEST_INSTALL_DIRECTORY}/$<CONFIG>")
