---
server:
  interface: "$local_interface:20100"
  addresses: ["$global_interface:20100", "$local_interface:20100"]

data_store:
  address: $mysql_address
  username: $mysql_username
  password: $mysql_password
  schema: $mysql_schema

service_locator:
  address: $service_locator_address
  username: administration_service
  password: $admin_password

organization: "Oasis World Trading Inc."

entitlements:
  - name: ASX Total
    price: 142.00
    currency: AUD
    group: asx_total
    applicability:
      - source: XASX
        messages: [BBO, BOOK, TAS, IMB]
  - name: CXA (TMX Australia)
    price: 68.50
    currency: USD
    group: chix_asx
    applicability:
      - source: CHIA
        messages: [BOOK, TAS, IMB]
  - name: Cboe Canada NEO Consolidated Level 1
    price: 22.10
    currency: CAD
    group: neoe
    applicability:
      - source: NEOE
        messages: [BBO, TAS]
  - name: Cboe Canada NEO-L Depth
    price: 32.90
    currency: CAD
    group: neoe_level_two
    applicability:
      - source: NEOE
        messages: [BOOK]
  - name: TSX Consolidated Level 1
    price: 107.55
    currency: CAD
    group: tsx_level_one
    applicability:
      - source: XTSE
        messages: [BBO, TAS]
  - name: TSX TL2
    price: 49.80
    currency: CAD
    group: tsx_level_two
    applicability:
      - source: XTSE
        messages: [BOOK]
  - name: TSXV Consolidated Level 1
    price: 76.50
    currency: CAD
    group: tsx_venture_level_one
    applicability:
      - source: XTSX
        messages: [BBO, TAS]
  - name: TSX Venture CL2
    price: 24.00
    currency: CAD
    group: tsx_venture_level_two
    applicability:
      - source: XTSX
        messages: [BOOK]
  - name: Alpha APD (TSX)
    price: 20.40
    currency: CAD
    group: alpha_apd_tsx
    applicability:
      - venue: XTSE
        source: XATS
        messages: [BOOK]
  - name: Alpha APD (TSX Venture)
    price: 3.80
    currency: CAD
    group: alpha_apd_tsxv
    applicability:
      - venue: XTSX
        source: XATS
        messages: [BOOK]
  - name: Alpha-X Depth
    price: 0.00
    currency: CAD
    group: alpha_x
    applicability:
      - source: XATX
        messages: [BOOK]
  - name: Nasdaq Canada CXC (TSX)
    price: 35.25
    currency: CAD
    group: chix_tsx
    applicability:
      - venue: XTSE
        source: CHIC
        messages: [BOOK]
  - name: Nasdaq Canada CXC (TSX Venture)
    price: 4.30
    currency: CAD
    group: chix_tsxv
    applicability:
      - venue: XTSX
        source: CHIC
        messages: [BOOK]
  - name: Nasdaq Canada CXC (CSE)
    price: 0.00
    currency: CAD
    group: chix_cse
    applicability:
      - venue: XCNQ
        source: CHIC
        messages: [BOOK]
  - name: Nasdaq Canada CXC (NEO)
    price: 0.00
    currency: CAD
    group: chix_neoe
    applicability:
      - venue: NEOE
        source: CHIC
        messages: [BOOK]
  - name: Nasdaq Canada CX2 Depth
    price: 21.95
    currency: CAD
    group: cx2_tsx
    applicability:
      - source: XCX2
        messages: [BOOK]
  - name: Lynx
    price: 0.00
    currency: CAD
    group: lynx
    applicability:
      - source: LYNX
        messages: [BOOK]
  - name: Cboe Canada NEO-N Depth
    price: 26.20
    currency: CAD
    group: neon
    applicability:
      - source: NEON
        messages: [BOOK]
  - name: Omega
    price: 21.00
    currency: CAD
    group: omega
    applicability:
      - source: OMGA
        messages: [BOOK]
  - name: CSE Consolidated Level 1
    price: 39.80
    currency: CAD
    group: cse
    applicability:
      - source: XCNQ
        messages: [BBO, TAS]
  - name: CSE, PURE and CSE2 Depth
    price: 25.50
    currency: CAD
    group: cse_level_two
    applicability:
      - source: XCNQ
        messages: [BOOK]
      - source: PURE
        messages: [BOOK]
      - source: CSE2
        messages: [BOOK]
  - name: OTC Markets
    price: 100.00
    currency: USD
    group: otcm
    applicability:
      - source: OTCM
        messages: [BBO, BOOK, TAS, IMB]
...
