---
service_locator:
  address: $service_locator_address
  username: $username
  password: $password

enable_logging: false
market: XNGO
disseminating_market: XNGO
mpid: NSE
time_zone: Asia/Tokyo
sampling: 100ms
host: 239.194.1.72:51072
interface: $local_interface:51072
...
