---
<<: !include "$common_config"

venue: LYNX
feeds:
  - address: "233.102.209.245:61021"
    interface: "$local_interface:61021"
  - address: "233.102.209.116:61022"
    interface: "$local_interface:61022"
recovery:
  address: "142.201.149.44:61029"
  delivery_address: "$local_interface:61068"
...
